abravalheri/validate-pyproject

- tests/test_plugins.py
See https://github.com/abravalheri/ini2toml/pull/28
> Fix problems with entry-point check in tests

- src/validate_pyproject/api.py
- src/validate_pyproject/formats.py
- tests/test_formats.py
> Fix problem with `trove-classifier` when detecting public format functions

- src/validate_pyproject/api.py
- src/validate_pyproject/vendoring/__init__.py
> Simplify implementation by relying on newly improved `fastjsonschema` API for compiling code

- src/validate_pyproject/formats.py
- tests/test_formats.py
> Allow private classifiers

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/invalid-examples/pretend-setuptools/dependencies/invalid-extra-name.errors.txt
- tests/invalid-examples/pretend-setuptools/dependencies/invalid-extra-name.toml
Related to https://github.com/pypa/setuptools/pull/3255
> Allow dependencies/optional-dependencies to use file directives

- CHANGELOG.rst
- setup.cfg
- src/validate_pyproject/cli.py
- tests/helpers.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_examples.py
- tests/test_pre_compile.py
> Use `tomllib` on Python >= 3.11

- .pre-commit-config.yaml
https://pypi.org/project/codespell as discussed in #62
> pre-commit: Add codespell to detect typos

- setup.cfg
This is motivated by:
- `https://github.com/pypa/wheel/issues/444`.
- https://github.com/abravalheri/validate-pyproject/commit/d4352efadd0cfa17555e8d9f004d0e9141b70e15
> Use dangling list for license_files.

- CHANGELOG.rst
- src/validate_pyproject/pre_compile/cli.py
- tests/pre_compile/test_cli.py
- tests/test_examples.py
- tests/test_pre_compile.py
Additionally, improve error message for invalid replacements in the ``pre_compile`` CLI.
> Minor fix in tests

- .git_archival.txt
- .gitattributes
- pyproject.toml
- setup.cfg
Fix #49.
Currently there are no tests for this option... Although it would be good to add some, it looks like a lot of overhead and complexity for a way of building that is considered "second tier"...
> Allow package to be build from git archive

- src/validate_pyproject/project_metadata.schema.json
- tests/invalid-examples/pep621/incorrect-subtables/author_with_extra_fields.errors.txt
- tests/invalid-examples/pep621/incorrect-subtables/author_with_extra_fields.toml
> Error-out when extra keys are added to project.authos/maintainers

- src/validate_pyproject/error_reporting.py
It seems that there was an error that got uncaught... Instead of adding `allOf`, we are checking for `anyOf` twice.
> Fix summary rewriting for `allOf`

- .readthedocs.yml
- docs/requirements.txt
- setup.cfg
- src/validate_pyproject/_tomllib.py
- src/validate_pyproject/cli.py
- tests/helpers.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_examples.py
- tests/test_pre_compile.py
- tests/test_repo_review.py
Given the failure in https://github.com/abravalheri/validate-pyproject/pull/106, I am experimenting with another approach.
> Address coverage problems for Python < 3.10

- .pre-commit-config.yaml
This isn't all that strict (I think it's following the official schema, which is pretty loose), but I think it's likely nice to have. Plus we can validate a couple of other schema while at it.
> chore: add schema validator check

- .ruff.toml
- docs/conf.py
- src/validate_pyproject/api.py
- src/validate_pyproject/cli.py
- src/validate_pyproject/formats.py
- src/validate_pyproject/plugins/__init__.py
- src/validate_pyproject/pre_compile/__init__.py
- src/validate_pyproject/pre_compile/cli.py
- tests/helpers.py
- tests/test_error_reporting.py
- tests/test_formats.py
- tests/test_plugins.py
Cleaning up the ruff config a bit after #97.
> chore: cleanup Ruff a bit

- tests/examples/cibuildwheel/test_config.json
- tests/examples/poetry/test_config.json
- tests/invalid-examples/cibuildwheel/test_config.json
- tests/invalid-examples/poetry/test_config.json
I forgot to update our tests when I changed this in SchemaStore.
> tests: update for partial renaming in SchemaStore

- pyproject.toml
- src/validate_pyproject/api.py
- src/validate_pyproject/cli.py
- src/validate_pyproject/error_reporting.py
- src/validate_pyproject/formats.py
- src/validate_pyproject/plugins/__init__.py
- src/validate_pyproject/pre_compile/cli.py
- src/validate_pyproject/remote.py
- src/validate_pyproject/vendoring/__init__.py
- src/validate_pyproject/vendoring/cli.py
- tox.ini
This adds more typing checking, enabling all but two strictness flags in mypy.
- chore(types): add more type annotations
- chore(types): enable more type checks
- chore(types): check for return Any
> chore: more typing

- .cirrus.yml
> ci: fix FreeBSD

- README.rst
- setup.cfg
Mentioning store plugin, adding as extra too.
> docs: add mention of store plugin

- src/validate_pyproject/formats.py
According to the discussion `pypa/packaging#705`.
> Update version regex according to latest packaging version

- .cirrus.yml
- .github/workflows/ci.yml
- .ruff.toml
- src/validate_pyproject/caching.py
- src/validate_pyproject/http.py
- src/validate_pyproject/remote.py
- tests/conftest.py
- tests/test_caching.py
- tools/cache_urls_for_tests.py
- tox.ini
The main idea is to avoid timeout errors and flaky tests.
> Use caching of external URLs during tests

- README.rst
> Fix indentation in readme's pre-commit config

- pyproject.toml
- tox.ini
This is the name reserved for the test-related extra.
> chore: rename testing extra to test

- src/validate_pyproject/project_metadata.schema.json
- tests/examples/simple/empty-author.toml
- tests/invalid-examples/pep621/missing-fields/empty-author.errors.txt
- tests/invalid-examples/pep621/missing-fields/empty-author.toml
> fix: verify author dict is not empty

- tests/test_formats.py
Discovered in https://github.com/abravalheri/validate-pyproject/pull/222 by linters.
> tests: fix test typo

- src/validate_pyproject/api.py
- src/validate_pyproject/plugins/__init__.py
- tests/test_plugins.py
> fix: more readable plugin id for stored plugins
