- .cirrus.yml
- .pre-commit-config.yaml
- src/validate_pyproject/formats.py
This commit updates versions of tools and containers used for running CI tasks.
See #2, https://github.com/pyscaffold/pyscaffold/pull/583.
> Update CI setup

- setup.cfg
It seems the code is compatible with `tomli==2.0.0`
> Remove upper pin from Tomli

- docs/json-schemas.rst
- docs/schemas.rst
- src/validate_pyproject/api.py
- src/validate_pyproject/project_metadata.schema.json
- src/validate_pyproject/pyproject_toml.schema.json
- tests/test_api.py
> Avoid naming schemas with specific PEP numbers

- src/validate_pyproject/formats.py
- tests/test_formats.py
According to the standard entry-points can be either in the form `importable.module`, or `importable.module:object.attr`, but currently `validate-pyproject` requires the second part.
> Fix entry-points format to allow values without the `:obj.attr` part

- src/validate_pyproject/formats.py
- tests/test_formats.py
Currently when embedded `validate-pyproject` will require users to add `trove-classifiers` to their dependencies. In some scenarios (e.g. `setuptools`) that may be very annoying (see comment in https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821/21).
A possible alternative is to download the classifiers directly from PyPI if the package is not installed, this is done by both [`distutils`](https://github.com/pypa/setuptools/blob/6193a69d8608b6ca7e0e5ac1223d63abb55eee3b/setuptools/_distutils/command/register.py#L85) and [`flit`](https://github.com/pypa/flit/blob/bdafdfec7158ba3774a47f7ed3d03645854a0540/flit/validate.py#L52).
This change adds the download as a fallback mechanism, but also skip this validation if the `NO_NETWORK` environment variable is used or …
> Improve trove classifier validation

- .github/workflows/ci.yml
- tox.ini
For the sake of minimizing resource utilization, gh-actions are only activated when pushing release tags.
> Add GH Actions for automatic test and release of tags

- src/validate_pyproject/formats.py
- tests/test_formats.py
Motivation:
> `setuptools._vendor._validate_pyproject.fastjsonschema_exceptions.JsonSchemaValueException`: data.urls.homepage must be url - my URL field did not start with ‘https://’, but [the example in PEP 621](https://www.python.org/dev/peps/pep-0621/#example) suggested this should work
>
> *originally posted in in (https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821)*
> Improve URL validation when scheme prefix is not present

- .cirrus.yml
- .github/workflows/ci.yml
- setup.cfg
- src/validate_pyproject/api.py
- tox.ini
For some reason the `typechecker` is failing in the GitHub action for Python 3.10, but not in the Cirrus CI.
Specifically the error is:
```
src/validate_pyproject/api.py:42: error: Module "importlib.resources" has no
attribute "files"  [attr-defined]
from importlib.resources import files
^
Found 1 error in 1 file (checked 24 source files)
```
The GHA environment is:
``
CPython (3.10.2)
mypy==0.931,
mypy-extensions==0.4.3,
packaging==21.3,
pyparsing==3.0.7,
tomli==2.0.1,
trove-classifiers==2022.2.16,
typing_extensions==4.1.1
```
The Cirrus CI environment is:
```
mypy==0.931,
mypy-extensions==0.4.3,
packaging==21.3,
pyparsing==3.0.7,
tomli==2.0.1,
trove-classifiers==2022.2.16,
typing_extensions==4.1.1,
```
Maybe the best solution here is to downgrade one of CirrusCI or GHA to use Python 3.9 …
```
> Use Python 3.10 in Cirrus CI for typecheck

- src/validate_pyproject/error_reporting.py
- src/validate_pyproject/extra_validations.py
- tests/invalid-examples/pdm/redefining-as-dynamic/errors.txt
Only set traceback in validation error if explicitly set in env var
> Avoid polluting `ValidationError` traceback with printing generate code 

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/examples/pretend-setuptools/04-pyproject.toml
- tests/examples/pretend-setuptools/07-pyproject.toml
- tests/invalid-examples/pretend-setuptools/pep621/license/empty.errors.txt
- tests/invalid-examples/pretend-setuptools/pep621/license/empty.toml
Place license-file in tool.setuptools instead of dynamic
Now that we clarified that PEP 621 does not specify anything about the (non-standard) core metadata field `License-file` and that it is not necessary to add `license` to `dynamic` to be able to automatically fill it, there is no motivation for keeping this field in `tool.setuptools.dynamic` instead of `tool.setuptools` (directly).
See:
- https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821/49
- https://discuss.python.org/t/help-testing-experimental-features-in-setuptools/13821/57
As such there is also little motivation to allow `license` and `license-files` in `dynamic`...
There is nothing else setuptools can do outside of what the standard already allows.
Even with PEP 639 (the draft currently …
> Remove `license` and `license-files` from `dynamic` in `setuptools` plugin.

- src/validate_pyproject/project_metadata.schema.json
- tests/examples/simple/dynamic-version.toml
- tests/examples/simple/minimal.toml
- tests/invalid-examples/pep621/missing-fields/missing-version-with-dynamic.errors.txt
- tests/invalid-examples/pep621/missing-fields/missing-version-with-dynamic.toml
- tests/invalid-examples/pep621/missing-fields/missing-version.errors.txt
- tests/invalid-examples/pep621/missing-fields/missing-version.toml
> Ensure `version` is given either statically or dynamically

- .pre-commit-config.yaml
- .pre-commit-hooks.yaml
- CHANGELOG.rst
- README.rst
- src/validate_pyproject/cli.py
- src/validate_pyproject/extra_validations.py
- src/validate_pyproject/pre_compile/cli.py
- tests/test_cli.py
The hook added by #40 seems to be called with all the files that match the file name `pyproject.toml`. However the CLI tool is only able to handle 1 file at time.
This change tries to fix that by allowing the CLI to validate multiple files.
Additionally, since this is the most common use case, the `files` regular expression is changed to only match `pyproject.toml` in the project root.
@wwuck, please let me know if you have any objections here.
> Fix pre-commit hook when called with multiple files

- README.rst
- src/validate_pyproject/project_metadata.schema.json
- tests/examples/atoml/pyproject.toml
- tests/examples/pdm/pyproject.toml
- tests/invalid-examples/pdm/invalid-version/pyproject.toml
- tests/invalid-examples/pdm/redefining-as-dynamic/pyproject.toml
Link directly to PEPs at their new home at https://peps.python.org/ rather than going via redirect at the old https://www.python.org/dev/peps/
(Split out from https://github.com/pypa/setuptools/pull/3770.)
> Link directly to PEPs

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/examples/setuptools/09-pyproject.toml
- tests/invalid-examples/setuptools/package-dir/invalid-stub.errors.txt
- tests/invalid-examples/setuptools/package-dir/invalid-stub.toml
> Allow PEP 561 stubs in `tool.setuptools.package-dir`

- CHANGELOG.rst
- src/validate_pyproject/plugins/setuptools.schema.json
See https://github.com/pypa/setuptools/issues/3874#issuecomment-1485860956.
> Fix problem with `license-files` in setuptools plugin

- src/validate_pyproject/cli.py
- tests/test_cli.py
This PR proposes showing a message when no file is passed telling that STDIN is being used.
Closes #94.
> Make it clear when using default input

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/invalid-examples/setuptools/attr/missing-attr-name.errors.txt
- tests/invalid-examples/setuptools/attr/missing-attr-name.toml
This change is motivated by the issue in pypa/setuptools#3928.
> Improve validation of `attr` directives for setuptools

- src/validate_pyproject/plugins/distutils.schema.json
- src/validate_pyproject/plugins/setuptools.schema.json
- tests/test_api.py
- tests/test_cli.py
See https://github.com/abravalheri/validate-pyproject/issues/110#issuecomment-1753301954
> Make `setuptools` schema definitions up-to-date.

- src/validate_pyproject/plugins/__init__.py
I was seeing
```
>       assert len(params.plugins) == 1
E       AssertionError: assert 2 == 1
E        +  where 2 = len([<validate_pyproject.plugins.PluginWrapper object at 0x1107e85d0>, <validate_pyproject.plugins.PluginWrapper object at 0x10fe8e810>])
E        +    where [<validate_pyproject.plugins.PluginWrapper object at 0x1107e85d0>, <validate_pyproject.plugins.PluginWrapper object at 0x10fe8e810>] = CliParams(input_file=[<_io.TextIOWrapper name='/private/var/folders/_8/xtbws09n017fbzdx9dmgnyyr0000gn/T/pytest-of-henryschreiner/pytest-7/test_parse_setuptools_distutil1/pyproject.toml' mode='r' encoding='UTF-8'>], plugins=[<validate_pyproject.plugins.PluginWrapper object at 0x1107e85d0>, <validate_pyproject.plugins.PluginWrapper object at 0x10fe8e810>], loglevel=30, …
```
> fix: plugin wrapper repr not helpful

- tests/test_cli.py
This makes the tests not break if a plugin is installed, see #114 (and all other PRs since that's breaking the CI currently).
> tests: tiny cleanup

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/examples/setuptools/readme-pyproject.toml
- tests/invalid-examples/setuptools/dynamic/readme-missing-file.errors.txt
- tests/invalid-examples/setuptools/dynamic/readme-missing-file.toml
- tests/invalid-examples/setuptools/dynamic/readme-too-many.errors.txt
- tests/invalid-examples/setuptools/dynamic/readme-too-many.toml
Forgot I found this small bug. It was possible to sneak extra keys in `tool.setuptools.dynamic.readme`.
> fix: setuptools readme field fix

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/invalid-examples/setuptools/attr/missing-attr-name.errors.txt
- tests/invalid-examples/setuptools/dependencies/invalid-extra-name.errors.txt
- tests/invalid-examples/setuptools/package-dir/invalid-stub.errors.txt
- tests/invalid-examples/setuptools/package-dir/invalid-stub.toml
- tests/invalid-examples/setuptools/packages/invalid-name.errors.txt
- tests/invalid-examples/setuptools/packages/invalid-stub-name.errors.txt
It's not clear if these are required or not, but I don't think it hurts.
> fix: add a few missing type keywords

- tools/to_schemastore.py
This is the script I'm using to prepare the schema for SchemaStore:
https://github.com/SchemaStore/schemastore/pull/3307
When producing that, I've applied #117 and #116 as well.
> chore: schemastore conversion script

- pyproject.toml
- setup.cfg
Moving a few things from setup.cfg to pyproject.toml.
Will follow up with mypy updates, but it's much easier to use Mypy's pyproject.toml config than the old ini config.
> chore: move a couple of configs to pyproject.toml

- .ruff.toml
Ruff is now using the lint prefix for lint-specific config.
> chore: modernize Ruff config

- src/validate_pyproject/formats.py
Just the added formats from #121.
Allowing unknown formats might also be nice.
> fix: support uint formats (used by Ruff)

- .pre-commit-config.yaml
This is faster, since it installs the mypyc compiled wheel of black instead of getting the source.
> chore: use 2x faster pre-commit mirror for Black

- pyproject.toml
- src/validate_pyproject/cli.py
- src/validate_pyproject/pre_compile/cli.py
- src/validate_pyproject/remote.py
- tests/examples/store/example.toml
- tests/examples/store/test_config.json
- tests/helpers.py
- tests/invalid-examples/store/cibw-overrides-noaction.errors.txt
- tests/invalid-examples/store/cibw-overrides-noaction.toml
- tests/invalid-examples/store/cibw-overrides-noselect.errors.txt
- tests/invalid-examples/store/cibw-overrides-noselect.toml
- tests/invalid-examples/store/cibw-unknown-option.errors.txt
- tests/invalid-examples/store/cibw-unknown-option.toml
- tests/invalid-examples/store/ruff-badcode.errors.txt
- tests/invalid-examples/store/ruff-badcode.toml
- tests/invalid-examples/store/ruff-unknown.errors.txt
- tests/invalid-examples/store/ruff-unknown.toml
- tests/invalid-examples/store/test_config.json
- tests/test_examples.py
- tests/test_pre_compile.py
This adds a `--store` option to load a schema store. I also considered `--tools`, and also considered requiring the fragment (`#/properties/tools/properties`), not sure which is best. I could see `--store` being expected to store something.
I'm also separately looking into a way to expose the "fragment" setting to classic plugins, since I think it would be useful to have a pinnable copy of the SchemaStore.
> feat: add --store to load a schema store

- .pre-commit-config.yaml
- CONTRIBUTING.rst
- src/validate_pyproject/plugins/__init__.py
This moves to using Ruff's black-like formatter instead of a separate tool. Soon, it will also be able to run on md/rst natively too, but for now (it takes some infrastructure changes to support reading in md/rst, it actually already understands them for docstrings), docs are still checked with blacken-docs. Simplifies things a bit and requires one less virtual environment and is faster. (It's not more elegantly integrated with the formatter, at least yet, though, though it does share config)
> chore: use ruff format instead of black

- src/validate_pyproject/pyproject_toml.schema.json
- tests/test_api.py
Now that https://packaging.python.org/en/latest/specifications/declaring-build-dependencies/ is working again, I think it is good to use it as reference, due to its significance.
See https://github.com/abravalheri/validate-pyproject/pull/147/files#r1465469332.
OBS: This reverts a previous change.
> Return more appropriate URL for [build-system] table

- .cirrus.yml
- src/validate_pyproject/pre_compile/__init__.py
Just a small something I noticed
> Remove duplicate `# ruff: noqa`

- CONTRIBUTING.rst
- docs/_gendocs.py
- docs/conf.py
- docs/embedding.rst
- docs/faq.rst
- docs/modules.rst.in
- src/validate_pyproject/api.py
- src/validate_pyproject/error_reporting.py
- src/validate_pyproject/errors.py
- src/validate_pyproject/formats.py
- tests/test_error_reporting.py
Right now the pages generated with `sphinx-apidoc` is a bit all over the place:
The idea of this change is to improve that and concentrate in the parts that make sense to expose as public.
It also improve some docstrings.
> Improve API docs

- .github/workflows/ci.yml
ARM is fine, but no Python 3.9 or earlier is not.
> ci: macos-latest now points at macos-14

- .cirrus.yml
Description of the problem: https://github.com/TheKevJames/coveralls-python/issues/434
> Add temporary workaround for coveralls (investigation)

- src/validate_pyproject/plugins/setuptools.schema.json
- tests/examples/setuptools/10-pyproject.toml
- tests/invalid-examples/setuptools/dependencies/invalid-extra-name.errors.txt
By analysing https://github.com/pypa/setuptools/issues/4341 we can see that currently `tool.setuptools.dynamic.optional-dependencies` differs from `project.optional-dependencies`.
They probably should be the same.
[PEP 685](https://peps.python.org/pep-0685/) also mentions that
> The [core metadata](https://packaging.python.org/en/latest/specifications/core-metadata/) specification will be updated such that the allowed names for [Provides-Extra](https://packaging.python.org/en/latest/specifications/core-metadata/#provides-extra-multiple-use) matches what [PEP 508](https://hugovk-peps.readthedocs.io/en/latest/pep-0508/) specifies for names.
So that makes sense for me.
> Align `tool.setuptools.dynamic.optional-dependencies` with `project.optional-dependencies`

- src/validate_pyproject/api.py
- src/validate_pyproject/plugins/__init__.py
- tests/test_api.py
This is one of the possibilities discussed in #174.
It seems to me that we should allow `--tool` (for example) to overwrite a plugin given by entry-points. We might have to re-evaluate this when adding the possibility of "side-loading" non-tool plugins.
I am not 100% sure if there are other unforeseen consequences of this change.
Multiple entry-points might also try to redefine the same entry? So we might want to improve the sorting to improve reproducibility.
> Allow overwrite when schemas refer to the same `tool`

- src/validate_pyproject/error_reporting.py
Whether `type_` is a `str` or  `list` is directly related to `value` being a `str` or `list`.
> Remove cast in error_reporting.py

- .cirrus.yml
Motivated by errors in the CI:
```
pkg: No packages available to install matching 'py39-pip' have been found in the repositories
pkg: No packages available to install matching 'py39-tox' have been found in the repositories
```
According the the following table in https://www.freshports.org/lang/python/ (07/08/2024), it seems that the default version of Python installed in FreeBSD 14 is Python 3.11 for the mainstream architectures.
> Update CI in FreeBSD to use Python 3.11

- src/validate_pyproject/formats.py
- src/validate_pyproject/plugins/setuptools.schema.json
- tests/invalid-examples/setuptools/packages/invalid-name.errors.txt
- tests/invalid-examples/setuptools/packages/invalid-name.toml
- tests/invalid-examples/setuptools/packages/invalid-stub-name.errors.txt
- tests/test_formats.py
Closes #162.
See details of the discussion in https://github.com/pypa/setuptools/issues/4316#issuecomment-2068123376.
> Relax requirements about module names to also allow dash characters

- .pre-commit-config.yaml
- pyproject.toml
- src/validate_pyproject/_tomllib.py
- src/validate_pyproject/formats.py
Follow-up of https://github.com/abravalheri/validate-pyproject/pull/187#issuecomment-2273640670.
> Apply assorted repo-review rules

- CHANGELOG.rst
- src/validate_pyproject/formats.py
> Fix misplaced comments on formats.py

- pyproject.toml
- tox.ini
Closes #200 
Possibly obviates #201 
The key aspect for the solution seems to be a `pytest` update and using `importlib` mode.
> Addopt `--import-mode=importlib` for pytest to prevent errors with `importlib.metadata`

- .cirrus.yml
This should fix the errors in macOS.
(Note: the latest PyScaffold templates try to minimise number of used minutes for Cirrus CI, since the free plan got more restrictive).
> Update Cirrus CI config from latest PyScaffold template

- .cirrus.yml
Hopefully, this is more economical to run in the CI (Cirrus CI have reduced the free plan a while ago).
> Attempt building and linting in a single task for Cirrus CI

- src/validate_pyproject/extra_validations.py
- src/validate_pyproject/pyproject_toml.schema.json
- tests/examples/simple/depgroups.toml
- tests/invalid-examples/pep735/invalid-group.errors.txt
- tests/invalid-examples/pep735/invalid-group.toml
- tests/invalid-examples/pep735/invalid-key.errors.txt
- tests/invalid-examples/pep735/invalid-key.toml
- tests/invalid-examples/pep735/not-pep508.errors.txt
- tests/invalid-examples/pep735/not-pep508.toml
Add support for validating PEP 735.
Pretty sure we can't validate that include-groups point to an existing group without custom code. Though maybe there is custom code for `dynamic` already? It doesn't seem to be part of the schema like in SchemaStore's version.
> feat: support PEP 735

- src/validate_pyproject/formats.py
- src/validate_pyproject/project_metadata.schema.json
- tests/examples/simple/pep638.toml
- tests/invalid-examples/pep621/pep639/bothstyles.errors.txt
- tests/invalid-examples/pep621/pep639/bothstyles.toml
Starting [PEP 639](https://peps.python.org/pep-0639/) support. It would be really nice to validate SPDX (wait for packaging?). I did make sure the incorrect combinations of license-files with non-string license is disallowed.
Close #70. I'm also adding support to SchemaStore's related file in https://github.com/SchemaStore/schemastore/pull/4143.
> feat: support PEP 639

- src/validate_pyproject/api.py
- tests/test_examples.py
- tests/test_pre_compile.py
Fix #197. The default for this param is becoming False in fastjsonschema 3.
> fix: don't modify by injecting defaults

- docs/dev-guide.rst
- src/validate_pyproject/cli.py
- src/validate_pyproject/plugins/__init__.py
- src/validate_pyproject/pre_compile/cli.py
- src/validate_pyproject/repo_review.py
- tests/test_plugins.py
This closes #144 and closes #134, using the "That is a good approach!" approach. :)
This adds a new entry point, `validate_pyproject.multi_schema`, that returns a dictionary with `tools` as well as extra `schemas`. We could later add more optional keys to this dict, so it's flexible, and the `tools` table allows fragments to be specified. This would allow validate-pyproject-schema-store to return all of it's known schemas in one entry point, rather than having to add an entry point for every table (and would allow the extra schemas to finally be present).
A few points for review:
* Check to make sure names are reasonable, I didn't think too long and hard about names.
* Should `tools` be a required key (currently not)? (Someone could always add an empty dict if they specified the rest with …
> feat: multi-plugins with extra schemas

- .cirrus.yml
- .readthedocs.yml
- docs/requirements.txt
- pyproject.toml
- tox.ini
Trying something new for RtD, based on recent additions. https://github.com/readthedocs/readthedocs.org/issues/11289 Also using tox-uv to speed up CI. This has the added bonus that `uv run pytest` also just works out of the box, since it picks up the `dev` dependency group. (Note: uv is not required for people running tox, though, just the minimum version was bumped a bit, no other changes for users)
This cuts the readthedocs job time in half. Other jobs are faster, too.
> chore: move to using dependency-groups

- docs/dev-guide.rst
Just fixing an oversight (possibly copy&paste error).
> Fix entry-point name in docs for `multi_schema`

- .github/workflows/ci.yml
The "explicit Python path" may not be necessary all the time, I did out of bad past experience with other Python's being picked up... (It is more verbose though...)
The `tox-uv` part is a follow up to include the same improvements as fond in https://github.com/abravalheri/validate-pyproject/pull/227
> CI: Update GHA to use `uvx` + `tox-uv`

- src/validate_pyproject/plugins/__init__.py
- tests/test_plugins.py
Found when working on https://github.com/henryiii/validate-pyproject-schema-store/pull/117. Looks like a unit testing bug. There might be an issue with getting the ordering wrong too (it's reporting all the tools are coming from the old location, which won't allow extra schemas to load). Looking into that, might be related though.
> fix: multi plugin id was read from the wrong place

- docs/dev-guide.rst
- src/validate_pyproject/plugins/__init__.py
- tests/test_plugins.py
Alternative to #242.
I am assuming the following:
- Plugins can be listed in any order, we just need this order to be consistent/reproducible.
- All schemas/tools that are returned by `list_from_entry_points` end up loaded in the registry, independently of the order in the list.
- There is no duplicates defining the same schemas/tools, because we remove them.
- We do need to stablish some sort of `priority/precedence` that tells us which plugin "wins" if multiple plugins specifies the same schema/tool.
- Again the specific choice of how the priorities are assigned is not important, what is important is the consistence/reproducibility.
Therefore, I think the following would be fine:
- tool plugins are listed first than other schemas,
- multi plugins always have higher priority, so they can …
> Proposal: Alternative plugin sorting

- docs/index.rst
Noticed this list was missing some PEPs.
> docs: add a few newer peps to docs list

- tests/examples/pdm/pyproject.toml
- tests/examples/pdm/test_config.json
The old example for pyproject.toml from pdm-backend had a section which is no longer valid:
```
[tool.pdm]
includes = ["pdm"]
source-includes = ["tests"]
```
The new format is:
```
[tool.pdm.build]
includes = ["src"]
source-includes = ["tests"]
```
For some context, I am prototyping a [TOML schema](https://github.com/udifuchs/toml-schema). For testing, I converted the full pyproject JSON schema to a TOML schema, and I am using your test examples for testing the TOML schema. This is how I noticed this issue.
> Update example from pdm-backend.
